#!/bin/sh
set -eu
IFS='
'

download_to=/storage/top_level_folder/
now=$(date +'%s')
while read -r line; do
	directory=$(echo "$line" | cut -f 1)
	url=$(echo "$line" | cut -f 2)
	feed=$({ curl -s --show-error "$url" || exit 1; } | sfeed)
	last_updated_directory="${XDG_CACHE_HOME:-$HOME/.cache}/rsstorrent"
	mkdir -p $last_updated_directory
	last_updated_file="$last_updated_directory/$directory"
	if [ -s "$last_updated_file" ]; then
		last_updated=$(date -d "@$(cat "$last_updated_file")" +'%s')
	else
		last_updated=0
	fi
	for entry in $feed; do
		timestamp=$(echo "$entry" | cut -f 1)
		name=$(echo "$entry" | cut -f 2)
		torrent=$(echo "$entry" | cut -f 3)
		if [ "$timestamp" -gt "$last_updated" ]; then
			transmission-remote -n 'user:pass' -w "$download_to/$directory" -a "$torrent"
		fi
	done
	echo "$now" > "$last_updated_file"
done
